#!/bin/sh
#
# $Id: env-shell.sh.in 2566 2016-05-05 18:14:22Z nega $
#
# Icetray environment script.
#
# THIS FILE WAS AUTOGENERATED.  ANY CHANGES YOU MAKE HERE WILL BE
# LOST.    IF YOU FIND YOURSELF NEEDING TO CHANGE THINGS HERE SEE
#
# http://wiki.icecube.wisc.edu/index.php/Shell_Configuration_Tips
# 
# [tds] If you need to change things here to make things work, that's
# a bug and you should *report* this to dataclass@icecube.wisc.edu or
# http://code.icecube.wisc.edu/projects/icecube/ .  Thanks for your help.  
#
if [ "$1" = "help" ]
    then
    echo "Usage: $0 [SHELL]"
    echo "Spawn a new shell with an Icetray environment loaded"
    echo ""
    echo "SHELL can specified with or without a full path.  If SHELL"
    echo "is omitted the login shell is used by default."
    echo "Examples:"
    echo "   ./env-shell.sh"
    echo "   ./env-shell.sh tcsh"
    echo "   ./env-shell.sh /bin/tcsh"
    echo ""
    echo "To exit the Icetray environment simply exit the new shell."
    echo ""
    exit 1
fi

if [ -z "$1" ]
    then # user did not specify a shell
    NEW_SHELL=$SHELL 
    # only exit if no shell specified on command line *and* env already loaded 
    if [ -n "$I3_SHELL" ] 
	then  
	echo "****************************************************************"
	echo "You are currently in a shell with an Icetray environment loaded."
	echo "Please exit the current shell and re-run $0 from a clean shell."
	echo "****************************************************************"
	echo "Environment not (re)loaded."
	exit 2
    fi
else
    NEW_SHELL=$1
    shift
    ARGV="$@"
fi

_I3_SHELL=$NEW_SHELL

_I3_PORTS=
_I3_SRC=/cr/data01/hagne/software/combo/src
_I3_BUILD=/cr/data01/hagne/software/combo/build
_I3_TESTDATA=
# If the I3_TESTDATA value at cmake time differs from the value
# that was set just prior to starting env-shell.sh, prefer the latter one.
# E.g.: user may have had both I3_PORTS and I3_TESTDATA undefined at cmake time,
# but then set I3_TESTDATA later.
if [ -d "$I3_TESTDATA" ]
then 
    if [ $(readlink "$_I3_TESTDATA") != $(readlink "$I3_TESTDATA") ]
    then
        _I3_TESTDATA=$I3_TESTDATA
    fi
fi
_PYVER=`python -V 2>&1`

# Check for I3_BUILD mismatch
if [ -n "$I3_BUILD" -a "$I3_BUILD" != "$_I3_BUILD" ]
then
    echo "****************************************************************"
    echo "I3_BUILD CHANGED"
    echo "It appears that you are attempting to load an icetray environment different"
    echo "than the one already loaded"
    echo "          This I3_BUILD=$_I3_BUILD"
    echo "Already loaded I3_BUILD=$I3_BUILD"
    echo "****************************************************************"
    echo "Environment not (re)loaded."
    exit 2
fi

# Check for valid ROOTSYS
if [ -d "/USE_ROOT/IS/OFF" ]; then

_ROOTSYS=/USE_ROOT/IS/OFF
_LD_LIBRARY_PATH=/cr/data01/hagne/software/combo/build/lib:/cr/data01/hagne/software/combo/build/lib/tools:${_ROOTSYS}/lib:/cr/data01/hagne/software/geant4/geant4.10.3-install/lib:$LD_LIBRARY_PATH
_DYLD_LIBRARY_PATH=/cr/data01/hagne/software/combo/build/lib:/cr/data01/hagne/software/combo/build/lib/tools:${_ROOTSYS}/lib:$_I3_PORTS/lib:$DYLD_LIBRARY_PATH

_PYTHONPATH=/cr/data01/hagne/software/combo/build/lib:${_ROOTSYS}/lib:$PYTHONPATH
if [ -z "$_I3_PORTS" ]; then
    _PATH=/cr/data01/hagne/software/combo/build/bin:${_ROOTSYS}/bin:$PATH
else
    _PATH=/cr/data01/hagne/software/combo/build/bin:${_ROOTSYS}/bin:$_I3_PORTS/bin:$PATH
fi

else

_ROOTSYS=''
_LD_LIBRARY_PATH=/cr/data01/hagne/software/combo/build/lib:/cr/data01/hagne/software/combo/build/lib/tools:/cr/data01/hagne/software/geant4/geant4.10.3-install/lib:$LD_LIBRARY_PATH
_DYLD_LIBRARY_PATH=/cr/data01/hagne/software/combo/build/lib:/cr/data01/hagne/software/combo/build/lib/tools:$_I3_PORTS/lib:$DYLD_LIBRARY_PATH

_PYTHONPATH=/cr/data01/hagne/software/combo/build/lib:$PYTHONPATH
if [ -z "$_I3_PORTS" ]; then
    _PATH=/cr/data01/hagne/software/combo/build/bin:$PATH
else
    _PATH=/cr/data01/hagne/software/combo/build/bin:$_I3_PORTS/bin:$PATH
fi

fi

_HIPPO_FOUND=
if [ "${_HIPPO_FOUND}" = 1 ]; then
    _LD_LIBRARY_PATH=::/usr/lib/x86_64-linux-gnu:${_LD_LIBRARY_PATH}
    _DYLD_LIBRARY_PATH=:${_DYLD_LIBRARY_PATH}
    _PYTHONPATH=:${_PYTHONPATH}
fi

TOPBAR="************************************************************************"
WIDTH=`echo "$TOPBAR" | wc -c`

WIDTH=$(( $WIDTH-2 ))

printctr()
{
    LEN=`echo "$*" | wc -c`
    LOFFSET=$(( ($WIDTH-$LEN)/2 ))
    ROFFSET=$(( $WIDTH-$LOFFSET-$LEN ))

    FORMAT="*%${LOFFSET}s%s%${ROFFSET}s*\n"
    printf $FORMAT " " "$*" " "
}

if [ -z "$ARGV" ]
    then
    printf "$TOPBAR\n"
    printctr ""
    printctr "W E L C O M E  to  I C E T R A Y"
    printctr ""
    printctr "Version combo.trunk     r153941"
    printctr ""
    printctr "You are welcome to visit our Web site"
    printctr "http://icecube.umd.edu"
    printctr ""
    printf "$TOPBAR\n"
    printf "\n"
    printf "Icetray environment has:\n"
    printf "   I3_SRC       = %s\n" $_I3_SRC
    printf "   I3_BUILD     = %s\n" $_I3_BUILD
    [ -z "$_I3_PORTS" ] || printf "   I3_PORTS     = %s\n" $_I3_PORTS
    [ -d "$_I3_TESTDATA" ] && printf "   I3_TESTDATA  = %s\n" $_I3_TESTDATA \
                           || printf "   I3_TESTDATA should be set to an existing directory path\n" \
                                     "   (and 'make rsync' may need to be run) if you wish to run tests."
    echo   "   Python       =" $_PYVER
fi

if [ -z "$I3_SHELL" ] # a clean, first invocation
    then

    # GEANT4_ENV_VARS pulls in GEANT4 variables,
    # generated by cmake/make_geant4_env.py

    PATH=$_PATH \
	LD_LIBRARY_PATH=$_LD_LIBRARY_PATH \
	DYLD_LIBRARY_PATH=$_DYLD_LIBRARY_PATH \
	PYTHONPATH=$_PYTHONPATH \
	ICETRAY_CLASSPATH=$_ICETRAY_CLASSPATH \
        I3_PLATFORM="" \
	I3_SRC=$_I3_SRC \
	I3_BUILD=$_I3_BUILD \
	I3_PORTS=$_I3_PORTS \
	I3_TESTDATA=$_I3_TESTDATA \
	ROOTSYS=$_ROOTSYS \
	I3_SHELL=$_I3_SHELL \
	G4LEVELGAMMADATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/PhotonEvaporation4.3.2 \
	G4PIIDATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/G4PII1.3 \
	G4NEUTRONXSDATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/G4NEUTRONXS1.4 \
	G4ABLADATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/G4ABLA3.0 \
	G4RADIOACTIVEDATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/RadioactiveDecay5.1.1 \
	G4LEDATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/G4EMLOW6.50 \
	G4NEUTRONHPDATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/G4NDL4.5 \
	G4REALSURFACEDATA=/cr/data01/hagne/software/geant4/geant4.10.3-install/share/Geant4-10.3.1/data/RealSurface1.0 \
	$NEW_SHELL "$@"

else  # not clean, use previous environment
    $NEW_SHELL "$@"
fi

STATUS=$?

if [ -z "$ARGV" ]
then
    echo "Exited Icetray Environment."
fi
exit $STATUS
